on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

name: continuous-integration

defaults:
  run:
    shell: nu {0}

env:
  NU_LOG_LEVEL: DEBUG

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-20.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: amtoine/setup-nupm-action@0.3.0
        with:
          nu_version: 0.96.0
          nupm_revision: 42d65a9

      # - name: Show Nushell Version
      #   run: version

      - name: Run the tests
        run: nu --commands $"use ($env.PWD)/nu-serde-bin/; nupm test"
